version: 2.1

docker:
    - image: circleci/python:3.7.3

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - sudo pip install pipenv
      - pipenv install

workflows:
  main:
    jobs:
      - build-and-test