version: 2.1

docker:
    - image: circleci/python:3.7.3

jobs:
  build-and-test:
    steps:
      - checkout
      - sudo pip install pipenv
      - pipenv install

workflows:
  version: 2.1
  build_test:
    jobs:
      - build-and-test